export const foodTypeList = [
    "Alcohol",
    "Beverages & Drinks", 
    "Breakfast",
    "Burgers",
    "Chinese",
    "Desserts",
    "Fast Food",
    "Halal",
    "Indian",
    "Italian",
    "Japanese",
    "Local",
    "Mexican",
    "Noodles",
    "Organic",
    "Pasta",
    "Pizza",
    "Salads",
    "Seafood",
    "Steak",
    "Sushi",
    "Tacos",
    "Tapas",
    "Vegetarian",
    "Western",
]